version: '3'
services:
  final:
    build: ./milestone_3
    ports:
      - "7860:7860"
    environment:
      - TF_ENABLE_ONEDNN_OPTS=0
    volumes:
      - image-volume:/final
    networks:
      - my-network

  # train_test:
  #   build: ./train_test
  #   ports:
  #     - "7861:7861"
  #   #depends_on:
  #   #  prep:
  #   #    condition: service_completed_successfully
  #   volumes:
  #     - image-volume:/prepped
  #     - image-volume:/output
  #   networks:
  #     - my-network

volumes:
  image-volume:

networks:
  my-network:
